labrin_task/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth import views as auth_views


from .views import signup, SignInView, ResetPasswordView, ConfirmPasswordResetView

urlpatterns = [
    url(r'^', include('todo.urls')),
    url(r'^login/$', SignInView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', signup, name='register'),
    url(r'^password_reset/$', ResetPasswordView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ConfirmPasswordResetView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),
]

todo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.TodoListView.as_view(), name='index'),
    url(r'^create-task/$', views.TodoCreateView.as_view(), name='create-todo'),
    url(r'^todos/(?P<pk>[0-9]+)/$', views.TodoDetailView.as_view(), name='todo-detail'),
    url(r'^todo/(?P<pk>[0-9]+)/delete/$', views.TodoDeleteView.as_view(), name='todo-delete'),
    url(r'^add-comment/$', views.CommentCreateView.as_view(), name='add-comment'),
    url(r'^share-task/$', views.ShareTodoView.as_view(), name='todo-share')
]

todo/models.py
from django.db import models
from django.contrib.auth import get_user_model

UserModel = get_user_model()


class Todo(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    deadline = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    text = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now_add=True)


class ShareTodo(models.Model):
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE)
    with_user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    comment_allowed = models.BooleanField(default=False)

todo/forms.py
from django import forms
from datetime import datetime


class CreateTodoForm(forms.Form):
    name = forms.CharField(max_length=64)
    description = forms.CharField(max_length=256)
    deadline = forms.DateTimeField(input_formats=["%m/%d/%Y %I:%M %p"])

    def clean_deadline(self):
        deadline = self.cleaned_data['deadline']
        if deadline < datetime.now():
            raise forms.ValidationError('Please choose future date')
        return deadline

todo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, FormView, DetailView, DeleteView
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, reverse

from .forms import CreateTodoForm
from .models import Todo, Comment, ShareTodo
from .utils import get_user_by_email_or_username, get_secs_until_10_minutes_before
from .tasks import send_todo_reminder


class TodoListView(LoginRequiredMixin, ListView):
    template_name = 'todo/index.html'
    context_object_name = 'todos'

    def get_queryset(self):
        return Todo.objects.filter(author=self.request.user) | \
            Todo.objects.filter(sharetodo__with_user=self.request.user)


class TodoCreateView(LoginRequiredMixin, FormView):
    form_class = CreateTodoForm
    template_name = 'todo/todo_create.html'
    success_url = '/'

    def form_valid(self, form):
        data = form.cleaned_data
        todo = Todo(name=data['name'],
                    description=data['description'],
                    deadline=data['deadline'])
        todo.author = self.request.user
        todo.save()
        print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
        print(get_secs_until_10_minutes_before(todo.deadline))
        send_todo_reminder.apply_async(
            args=(self.request.user.email, todo.name),
            countdown=get_secs_until_10_minutes_before(todo.deadline)
        )
        return HttpResponseRedirect(reverse('index'))

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form})


class TodoDetailView(LoginRequiredMixin, DetailView):
    model = Todo
    context_object_name = 'todo'
    template_name = 'todo/todo_detail.html'

    def get_context_data(self, **kwargs):
        context = super(TodoDetailView, self).get_context_data(**kwargs)
        instance = self.object
        if self.request.user != instance.author:
            share_obj = ShareTodo.objects.filter(todo=instance, with_user=self.request.user)
            share_obj = share_obj.last() if share_obj.exists() else None
            if share_obj and not share_obj.comment_allowed:
                context['comment_allowed'] = False
            else:
                context['comment_allowed'] = True
        else:
            context['comment_allowed'] = True
        context['comment_list'] = instance.comment_set.all().order_by('-created_at')
        context['todo_id'] = instance.pk
        return context


class CommentCreateView(LoginRequiredMixin, FormView):
    template_name = 'todo/comments.html'

    def post(self, request, *args, **kwargs):
        text = request.POST.get('text', False)
        related_todo_id = request.POST.get('todo_id', False)
        todo_queryset = Todo.objects.filter(pk=related_todo_id)
        if not todo_queryset.exists():
            return JsonResponse({
                'error': 'true',
                'msg': 'Invalid task object'
            })
        else:
            todo_obj = todo_queryset.last()
        if todo_obj.author != request.user:
            share_obj = ShareTodo.objects.filter(todo=todo_obj, with_user=self.request.user)
            share_obj = share_obj.last() if share_obj.exists() else None
            if share_obj and not share_obj.comment_allowed:
                return JsonResponse({
                    'error': 'true',
                    'msg': 'Unauthorized'
                })
            return JsonResponse({
                'error': 'true',
                'msg': 'Unauthorized'
            })

        if text and not text.isspace():
            Comment.objects.create(todo=todo_obj, author=request.user, text=text)
            comment_list = todo_obj.comment_set.all().order_by('-created_at')
            return render(request, self.template_name, {
                'comment_list': comment_list,
                'todo_id': todo_obj.pk,
                'comment_allowed': True
            })


class TodoDeleteView(UserPassesTestMixin, DeleteView):
    model = Todo
    success_url = '/'

    def test_func(self):
        todo = Todo.objects.get(pk=self.kwargs['pk'])
        return self.request.user == todo.author


class ShareTodoView(LoginRequiredMixin, FormView):
    def post(self, request, *args, **kwargs):
        todo_id = request.POST.get('todo_id', False)
        with_user = request.POST.get('user', False)
        allow_comment = request.POST.get('allow_comment', False)
        user_obj = get_user_by_email_or_username(with_user)
        if not user_obj:
            return JsonResponse({
                'msg': 'Invalid user'
            })
        allow_comment = True if allow_comment == 'checked' else False
        todo = Todo.objects.get(pk=todo_id)
        if todo.author != self.request.user:
            return JsonResponse({
                'msg': 'Unauthorized'
            })
        share_obj, created = ShareTodo.objects.get_or_create(todo=todo,
                                                             with_user=user_obj)
        if not created:
            return JsonResponse({
                'msg': 'This task already shared with {}'.format(user_obj.username)
            })
        else:
            share_obj.comment_allowed = allow_comment
            share_obj.save()
        return JsonResponse({
            'success': 'true'
        })

todo/templates/todo/comments.html
{% if comment_allowed %}
  <h3>Add comment</h3>
  <form method="post">{% csrf_token %}
    <div class="form-row">
      <div class="form-group full-textarea">
        <textarea class="form-control comment-text" name="comment" cols="40" rows="2" ></textarea>
      </div>
    </div>
    <button type="submit" id="id_comment" todo-id="{{ todo_id }}" class="btn btn-primary add-comment">
      Comment
    </button>
  </form>
  <hr>
{% else %}
  <p class="text-warning">You are not allowed to comment here by the auhtor of this task.</p>
{% endif %}
<h4>Comments</h4>
<div class="card" style="width: 100%;">
  <ul class="list-group list-group-flush comment-list">
    {% for comment in comment_list %}

      <li class="list-group-item">
        <p class="small">{{ comment.created_at|date:"b d h:i a" }} - {{ comment.author.username }}</p>
        {{ comment.text }}</li>
    {% empty %}
    {% endfor %}
  </ul>
</div>

todo/templates/todo/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h1>{{ header1 }}</h1>
    <a class="btn btn-primary" href="{% url 'create-todo' %}">Add Task</a>
    {% for todo in todos %}
      <div class="card w-100" style="margin-top: 10px;">
        <div class="card-body" style="padding: 5px">
            <h5 class="card-title">{{ todo.name }}</h5>
            <small style="display: block">{{ todo.author }}</small>
            <a href="{% url 'todo-detail' todo.pk %}" class="btn btn-primary">Details</a>
            {% if request.user == todo.author %}
              <a class="btn btn-primary float-right ml-1" href="{% url 'todo-delete' todo.pk %}"
                 data-toggle="modal" data-target="#todo-delete-{{ todo.pk }}">
                <span class="fas fa-trash" title="Delete Task"></span>
              </a>
              <a class="btn btn-primary float-right" href="{% url 'todo-share' %}"
                 data-toggle="modal" data-target="#todo-share-{{ todo.pk }}">
                <span class="fas fa-share-alt" title="Share Task"></span>
              </a>
            {% endif %}
        </div>
      </div>

      <!-- TODO_ DELETE MODAL -->
      <div class="modal fade" id="todo-delete-{{ todo.pk }}" tabindex="-1" role="dialog"
             aria-labelledby="deleteTodo{{ todo.pk }}" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteTodo{{ todo.pk }}">Remove task '{{ todo.name }}'</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>
                  Do you want to remove this task?
                </p>
              </div>
              <div class="modal-footer">
                <form method="post" action="{% url 'todo-delete' todo.pk %}">{% csrf_token %}
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  <button type="submit" class="btn btn-primary" value="Confirm">Remove</button>
                </form>
              </div>
            </div>
        </div>
      </div>

      <!-- TODO_ SHARE MODAL -->
      <div class="modal fade" id="todo-share-{{ todo.pk }}" tabindex="-1" role="dialog"
             aria-labelledby="shareTodo{{ todo.pk }}" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="shareTodo{{ todo.pk }}">Share task '{{ todo.name }}'</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <form method="post" action="">{% csrf_token %}
                <div class="modal-body">
                  <div class="form-group">
                    <label for="inputShareUser">With user:</label>
                    <input type="text" class="form-control" id="inputShareUser-{{ todo.pk }}"
                           placeholder="Enter email or username" name="user">
                  </div>
                  <div class="form-group form-check">
                    <input type="checkbox" class="form-check-input"
                           id="shareAllowComment-{{ todo.pk }}" name="allow_comment">
                    <label class="form-check-label" for="shareAllowComment">Allow to comment</label>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-primary share-task"
                          todo-id="{{ todo.pk }}" value="Confirm">
                    Share
                  </button>
                </div>
              </form>
            </div>
        </div>
      </div>
    {% empty %}
      {% autoescape off %}
      <p>You didn't create any task yet.</p>
      {% endautoescape %}
    {% endfor %}
  </div>
</div>
{% endblock %}

todo/templates/todo/todo_create.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
  {% if form.errors %}
    {% for error in form.non_field_errors %}
      <p class="text-danger">{{ error }}</p>
    {% endfor %}
    {% for field in form %}
      {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="id_name">Name</label>
      <input type="text" id="id_name" name="name" class="form-control">
    </div>
    <div class="form-group col-md-6">
{#      <label for="{{ form.deadline.id_for_label }}">Deadline</label>#}
{#      {{ form.deadline }}#}
      <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
{#        <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>#}
        <label for="id_deadline">Deadline</label>
        <input id="id_deadline" class="form-control datetimepicker-input datetimer-custom"
               type="text" name="deadline" target="#datetimepicker1">
        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="far fa-calendar"></i></div>
        </div>
      </div>
    </div>
  </div>
	<div class="form-row">
    <div class="form-group full-textarea">
      <label for="id_description">Description</label>
      <textarea id="id_description" class="form-control"
                name="description" cols="40" rows="10" ></textarea>
    </div>
	</div>
  <button type="submit" class="btn btn-primary">Create</button>
</form>

<script type="text/javascript">
  $(function () {
    $('#id_deadline').datetimepicker();
  });
</script>

{% endblock %}

todo/templates/todo/todo_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ todo.name }}</h1>
<p>{{ todo.description }}</p>

<hr>
<div class="comments-container">
  {% include 'todo/comments.html' %}
</div>

{% endblock %}

{% block websocket-script %}

<script>
  function getCommentHTML(data) {
    return (
      "<li class=\"list-group-item\">" +
      "<p class=\"small\">" + data.date.toLowerCase() + " - " + data.user_name +
      "</p>" + data.text + "</li>"
    )
  }

  var commentSocket = new WebSocket('ws://' + window.location.host + '/comment/' + {{ todo.id }} +'/');

  commentSocket.onopen = function open() {
    console.log('CONNECTED')
  };

  if (commentSocket.readyState == WebSocket.OPEN) {
    commentSocket.onopen();
  }

  commentSocket.onmessage = function message(e) {
    var data = JSON.parse(e.data);
    var commentHTML = getCommentHTML(data);
    $('.comment-list').prepend(commentHTML);
  };

  $('.add-comment').on('click', function (e) {
    e.preventDefault();
    var text = $('.comment-text').val().trim();
    if (text !== "") {
      commentSocket.send(JSON.stringify(
        {
          'message': text
        }
      ));
      $('.comment-text').val("");
    }
  })

</script>

{% endblock %}